"""Stage 3 stepwise G1 closure gate.

This module drives the differential testing of the Lean ``StepKernel`` against
two independent clingo oracles:

* **Global entailment** — every Lean ``ACCEPT_STEP`` must be globally forced
  under ``Puzzle + StepState``. The gate records a counterexample model for
  any disagreement and counts it as one ``unsound_accept``.

* **Justification-local entailment** — for supported local place/eliminate
  consequence rules, the Lean verdict must match an independent clingo query
  built from the bijection base, the StepState, and (for clue-backed rules)
  the single cited clue only. The gate records a ``local_differential_disagree``
  for every disagreement.

The corpus is the union of:

* the 1,000 gold ZebraLogic puzzles re-emitted from the committed
  ``compiled_problems.jsonl`` (no external ``data/zebralogic/source.json``
  required)
* at least 10,000 deterministically fuzzed random puzzles generated by
  :mod:`sparseir_harness.fuzzed_puzzles`

The gate writes:

* ``manifest.json`` — frozen provenance + headline counts
* ``config.json`` — generator configuration and inputs
* ``summary.md`` — human-readable roll-up
* ``DESIGN.md`` — design note documenting the global vs local oracle
  distinction (copied from the module docstring on first run)
* ``step_cases.jsonl`` — every step query, including rejected semantic steps
* ``results.jsonl`` — Lean verdict plus both oracle verdicts per case
* ``disagreements.jsonl`` — every disagreement (empty at freeze)
* ``counterexamples.jsonl`` — clingo counterexample models that disprove a
  Lean-accepted step (empty at freeze)
* ``coverage.json`` — per-rule and per-clue-type counts
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import subprocess
from collections import Counter
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from pathlib import Path
from typing import Any

try:
    import clingo as _clingo
except ImportError:  # pragma: no cover - exercised by missing-clingo gate test
    _clingo = None

from .clingo_step_oracle import (
    CLUE_TYPES,
    PLACE_RULES,
    ELIMINATE_RULES,
    check_global_entailment,
    check_local_entailment,
    is_local_differential_rule,
    state_is_sat,
)
from .problem_fabricator import fabric_corpus
from .fuzzed_puzzles import (
    fuzz_grid_distribution,
    generate_fuzzed_puzzles,
)
from .reference_solutions import ROOT
from .step_state_generator import (
    generate_states,
)
from .step_proposer import (
    PLACE_RULES as PROPOSER_PLACE_RULES,
    ELIMINATE_RULES as PROPOSER_ELIMINATE_RULES,
    propose_steps,
)


FUZZ_MIN_COUNT = 10000
GOLD_GRID_MIN = 1
DEFAULT_STATES_PER_PUZZLE = 6
DEFAULT_STEPS_PER_STATE = 12
SUPPORTED_DIFFERENTIAL_RULES = frozenset(PROPOSER_PLACE_RULES) | frozenset(PROPOSER_ELIMINATE_RULES)


@dataclass
class GateConfig:
    compiled_path: Path
    reference_dir: Path
    output_dir: Path
    fuzz_seed: int
    fuzz_count: int
    states_per_puzzle: int
    steps_per_state: int
    clingo_timeout_seconds: float
    seed: int
    lean_executable: Path | None
    fuzz_grid_distribution: dict[str, int]


def _clingo_version() -> str:
    if _clingo is None:
        return "unavailable"
    return getattr(_clingo, "__version__", "unknown")


def _lean_identity(executable: Path | None) -> dict[str, str]:
    if executable is None or not executable.is_file():
        return {"executable": "lake-exe-sparse-ir-lean"}
    digest = hashlib.sha256(executable.read_bytes()).hexdigest()
    return {
        "executable": str(executable),
        "sha256": digest,
        "size_bytes": str(executable.stat().st_size),
    }


def _read_reference_solutions(reference_dir: Path) -> dict[str, dict[str, Any]]:
    path = reference_dir / "reference_solutions.jsonl"
    if not path.is_file():
        return {}
    rows = [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    return {row["source_problem_id"]: row["candidate"] for row in rows}


def _stage_a_fabricated_dir(output_dir: Path) -> Path:
    return output_dir / "fabricated_problems"


def _stage_a_corpus(config: GateConfig) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    fabricated_dir = _stage_a_fabricated_dir(config.output_dir)
    problems, provenance = fabric_corpus(config.compiled_path, fabricated_dir)
    provenance["fabricated_dir"] = str(fabricated_dir)
    provenance["input_count"] = len(problems)
    return problems, provenance


def _stage_a_reference_corpus(
    problems: list[dict[str, Any]],
    reference_dir: Path,
) -> tuple[dict[str, dict[str, dict[str, str]]], dict[str, Any]]:
    references = _read_reference_solutions(reference_dir)
    fallback: dict[str, dict[str, dict[str, str]]] = {}
    missing: list[str] = []
    by_id = {problem["id"]: problem for problem in problems}
    for problem_id, candidate in references.items():
        if problem_id not in by_id:
            missing.append(problem_id)
            continue
        fallback[problem_id] = candidate.get("solution", {})
    return fallback, {"matched": len(fallback), "missing": missing}


def _strip_fuzz_meta(problem: dict[str, Any]) -> dict[str, Any]:
    return {key: value for key, value in problem.items() if not key.startswith("_")}


def _reference_for(problem: dict[str, Any], stage_a_ref: dict[str, dict[str, dict[str, str]]]) -> dict[str, dict[str, str]]:
    if problem["id"] in stage_a_ref:
        return stage_a_ref[problem["id"]]
    return problem.get("_fuzz_meta", {}).get("satisfaction", {})


def _build_corpus(
    config: GateConfig,
    stage_a_provenance: dict[str, Any],
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    stage_a_problems, _ = _stage_a_corpus(config)
    stage_a_references, reference_provenance = _stage_a_reference_corpus(
        stage_a_problems, config.reference_dir
    )
    stage_a_corpus: list[dict[str, Any]] = []
    stage_a_missing: list[str] = []
    for problem in stage_a_problems:
        ref = _reference_for(problem, stage_a_references)
        if not ref:
            stage_a_missing.append(problem["id"])
            continue
        stage_a_corpus.append({**problem, "_reference": ref})
    fuzz_problems = generate_fuzzed_puzzles(config.fuzz_seed, config.fuzz_count)
    fuzz_corpus: list[dict[str, Any]] = []
    for problem in fuzz_problems:
        ref = _reference_for(problem, stage_a_references)
        if not ref:
            continue
        fuzz_corpus.append({**problem, "_reference": ref})
    corpus_provenance = {
        "stage2a_provenance": stage_a_provenance,
        "stage2a_problem_count": len(stage_a_problems),
        "stage2a_corpus_count": len(stage_a_corpus),
        "stage2a_missing_references": stage_a_missing,
        "stage2a_reference_provenance": reference_provenance,
        "fuzz_seed": config.fuzz_seed,
        "fuzz_count": config.fuzz_count,
        "fuzz_grid_distribution": fuzz_grid_distribution(fuzz_problems),
        "total_corpus_count": len(stage_a_corpus) + len(fuzz_corpus),
    }
    return stage_a_corpus, fuzz_corpus, corpus_provenance


def _state_query_count(puzzle: dict[str, Any], config: GateConfig) -> int:
    return config.states_per_puzzle


def _enumerate_case_plan(
    puzzles: list[dict[str, Any]],
    config: GateConfig,
) -> list[tuple[dict[str, Any], dict[str, Any], dict[str, Any]]]:
    plan: list[tuple[dict[str, Any], dict[str, Any], dict[str, Any]]] = []
    for puzzle_index, puzzle in enumerate(puzzles):
        reference = puzzle["_reference"]
        states = generate_states(
            _strip_fuzz_meta(puzzle),
            reference,
            seed=config.seed + puzzle_index,
            count=_state_query_count(puzzle, config),
        )
        for state_index, state in enumerate(states):
            proposals = propose_steps(
                _strip_fuzz_meta(puzzle),
                state,
                seed=config.seed + puzzle_index * 1009 + state_index,
                max_proposals=config.steps_per_state,
            )
            for step_index, step in enumerate(proposals):
                plan.append((puzzle, state, step))
    return plan


def _invoke_lean(
    payload: dict[str, Any],
    executable: Path | None,
) -> dict[str, Any]:
    if executable is not None:
        command = [str(executable)]
    else:
        lake = shutil.which("lake")
        if lake is None:
            raise RuntimeError("lake was not found on PATH")
        command = [lake, "exe", "sparse-ir-lean"]
    completed = subprocess.run(
        command,
        input=json.dumps(payload),
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(
            f"Lean verifier exited with {completed.returncode}: {completed.stderr.strip()}"
        )
    return json.loads(completed.stdout)


def _lean_state_for_init(problem: dict[str, Any], executable: Path | None) -> dict[str, Any] | None:
    request = {
        "protocol_version": "0.1.0",
        "request_id": "init-state",
        "command": "init_state",
        "payload": {"problem": json.dumps(_strip_fuzz_meta(problem))},
    }
    try:
        result = _invoke_lean(request, executable)["result"]
    except Exception:
        return None
    if result.get("kind") != "STATE_INITIALIZED":
        return None
    return result["state"]


def _lean_check_step(
    problem: dict[str, Any],
    state: dict[str, Any],
    step: dict[str, Any],
    executable: Path | None,
) -> dict[str, Any]:
    request = {
        "protocol_version": "0.1.0",
        "request_id": "check-step",
        "command": "check_step",
        "payload": {
            "problem": json.dumps(_strip_fuzz_meta(problem)),
            "state": json.dumps(state),
            "step": json.dumps(step),
        },
    }
    return _invoke_lean(request, executable)["result"]


def _clue_type_of_rule(rule: str) -> str | None:
    mapping = {
        "given_found_at_place": "found_at",
        "given_not_at_eliminate": "not_at",
        "same_house_place_from_placed": "same_house",
        "same_house_eliminate_no_possible_match": "same_house",
        "direct_left_place_from_fixed": "direct_left",
        "direct_left_eliminate_no_possible_partner": "direct_left",
        "direct_right_place_from_fixed": "direct_right",
        "direct_right_eliminate_no_possible_partner": "direct_right",
        "side_by_side_place_from_single_neighbor": "side_by_side",
        "side_by_side_eliminate_no_possible_neighbor": "side_by_side",
        "left_of_eliminate_impossible_order": "left_of",
        "right_of_eliminate_impossible_order": "right_of",
        "one_between_place_from_fixed": "one_between",
        "one_between_eliminate_no_possible_partner": "one_between",
        "two_between_place_from_fixed": "two_between",
        "two_between_eliminate_no_possible_partner": "two_between",
    }
    return mapping.get(rule)


def _evaluate_case(
    case: tuple[dict[str, Any], dict[str, Any], dict[str, Any], int, int, int],
) -> dict[str, Any]:
    problem, state, step, puzzle_index, state_index, step_index = case
    rule = step.get("justify", {}).get("rule")
    clue_id = step.get("justify", {}).get("clue_id")
    op = step.get("op")
    clean_problem = _strip_fuzz_meta(problem)
    sat_outcome = state_is_sat(clean_problem, state)
    if sat_outcome.status != "sat":
        return {
            "case_id": f"case-{puzzle_index:05d}-{state_index:03d}-{step_index:03d}",
            "puzzle_id": problem["id"],
            "puzzle_kind": "fuzz" if problem["source"]["dataset"] == "zebralogic" and problem["source"]["split"] == "fuzz" else "gold",
            "grid": problem["source"]["grid"],
            "state_index": state_index,
            "step_index": step_index,
            "step": step,
            "state_sat_status": sat_outcome.status,
            "included_in_corpus": False,
        }
    lean_result = _lean_check_step(clean_problem, state, step, executable=None)
    accepted = lean_result.get("kind") == "ACCEPT_STEP"
    local_outcome = None
    if op in {"place", "eliminate"} and is_local_differential_rule(rule):
        local_outcome = check_local_entailment(
            clean_problem,
            state,
            op=op,
            item={"cat": step["cat"], "val": step["val"]},
            house=int(step["house"]),
            rule=rule,
            clue_id=clue_id,
        )
    global_outcome = check_global_entailment(
        clean_problem,
        state,
        op=op,
        item={"cat": step["cat"], "val": step["val"]},
        house=int(step["house"]),
    ) if op in {"place", "eliminate"} else None
    return {
        "case_id": f"case-{puzzle_index:05d}-{state_index:03d}-{state_index:03d}-{step_index:03d}",
        "puzzle_id": problem["id"],
        "puzzle_kind": "fuzz" if problem["source"]["dataset"] == "zebralogic" and problem["source"]["split"] == "fuzz" else "gold",
        "grid": problem["source"]["grid"],
        "state_index": state_index,
        "step_index": step_index,
        "step": step,
        "state_sat_status": sat_outcome.status,
        "included_in_corpus": True,
        "lean_result": lean_result,
        "lean_accepted": accepted,
        "global_oracle": _outcome_to_dict(global_outcome),
        "local_oracle": _outcome_to_dict(local_outcome),
        "rule": rule,
        "clue_type": _clue_type_of_rule(rule) if rule else None,
        "is_local_differential_rule": is_local_differential_rule(rule) if rule else False,
    }


def _outcome_to_dict(outcome: Any) -> dict[str, Any] | None:
    if outcome is None:
        return None
    return {
        "status": outcome.status,
        "satisfiable": outcome.satisfiable,
        "elapsed_seconds": round(outcome.elapsed_seconds, 6),
        "model": outcome.model,
        "message": outcome.message,
    }


def _run_gate(config: GateConfig) -> dict[str, Any]:
    output = config.output_dir
    output.mkdir(parents=True, exist_ok=True)
    state_a_problems, fuzz_problems, corpus_provenance = _build_corpus(config, stage_a_provenance={})
    executable_path = ROOT / ".lake" / "build" / "bin" / "sparse-ir-lean"
    executable = executable_path if executable_path.is_file() else None
    corpus_provenance["lean_executable"] = _lean_identity(executable)
    corpus_provenance["clingo_version"] = _clingo_version()
    corpus_provenance["oracle_encoding"] = "stage3-stepwise-g1-v1"
    all_puzzles = state_a_problems + fuzz_problems
    plan: list[tuple[dict[str, Any], dict[str, Any], dict[str, Any], int, int, int]] = []
    for puzzle_index, puzzle in enumerate(all_puzzles):
        clean_problem = _strip_fuzz_meta(puzzle)
        reference = puzzle["_reference"]
        states = generate_states(
            clean_problem,
            reference,
            seed=config.seed + puzzle_index,
            count=_state_query_count(puzzle, config),
        )
        for state_index, state in enumerate(states):
            proposals = propose_steps(
                clean_problem,
                state,
                seed=config.seed + puzzle_index * 1009 + state_index,
                max_proposals=config.steps_per_state,
            )
            for step_index, step in enumerate(proposals):
                plan.append((puzzle, state, step, puzzle_index, state_index, step_index))
    print(f"plan size: {len(plan)} cases", flush=True)
    rows: list[dict[str, Any]] = []
    if plan:
        with ThreadPoolExecutor(max_workers=min(8, os.cpu_count() or 1)) as executor:
            for index, row in enumerate(executor.map(_evaluate_case, plan), start=1):
                rows.append(row)
                if index % 250 == 0 or index == len(plan):
                    print(f"evaluated {index}/{len(plan)} cases", flush=True)
    return _finalize(rows, config, corpus_provenance)


def _finalize(
    rows: list[dict[str, Any]],
    config: GateConfig,
    corpus_provenance: dict[str, Any],
) -> dict[str, Any]:
    output = config.output_dir
    sat_states = [row for row in rows if row.get("state_sat_status") == "sat"]
    disagreements: list[dict[str, Any]] = []
    counterexamples: list[dict[str, Any]] = []
    unsound_accepts = 0
    local_differential_disagrees = 0
    for row in sat_states:
        if row.get("lean_accepted"):
            global_outcome = row.get("global_oracle") or {}
            if global_outcome.get("status") == "sat":
                unsound_accepts += 1
                counterexamples.append(
                    {
                        "case_id": row["case_id"],
                        "puzzle_id": row["puzzle_id"],
                        "grid": row["grid"],
                        "step": row["step"],
                        "global_model": global_outcome.get("model"),
                        "elapsed_seconds": global_outcome.get("elapsed_seconds"),
                    }
                )
                disagreements.append(
                    {
                        "disagreement_type": "unsound_lean_accept",
                        "case_id": row["case_id"],
                        "puzzle_id": row["puzzle_id"],
                        "grid": row["grid"],
                        "step": row["step"],
                        "lean_result": row["lean_result"],
                        "global_oracle": global_outcome,
                        "rule": row.get("rule"),
                        "clue_type": row.get("clue_type"),
                    }
                )
        if row.get("is_local_differential_rule"):
            local_outcome = row.get("local_oracle") or {}
            local_unsat = local_outcome.get("status") == "unsat"
            lean_local_accept = bool(row.get("lean_accepted"))
            if lean_local_accept != local_unsat:
                local_differential_disagrees += 1
                disagreements.append(
                    {
                        "disagreement_type": "local_differential",
                        "case_id": row["case_id"],
                        "puzzle_id": row["puzzle_id"],
                        "grid": row["grid"],
                        "step": row["step"],
                        "lean_result": row["lean_result"],
                        "local_oracle": local_outcome,
                        "rule": row.get("rule"),
                        "clue_type": row.get("clue_type"),
                    }
                )
    summary_stats = _summarize(rows, sat_states, unsound_accepts, local_differential_disagrees)
    manifest = {
        "gate": "stage3_stepwise_g1",
        "status": _gate_status(unsound_accepts, local_differential_disagrees, summary_stats, fuzz_count=config.fuzz_count),
        "seed": config.seed,
        "fuzz_seed": config.fuzz_seed,
        "clingo_version": _clingo_version(),
        "corpus_provenance": corpus_provenance,
        "summary": summary_stats,
        "disagreement_count": len(disagreements),
        "counterexample_count": len(counterexamples),
    }
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    config_payload = {
        "compiled_path": str(config.compiled_path),
        "reference_dir": str(config.reference_dir),
        "output_dir": str(config.output_dir),
        "fuzz_seed": config.fuzz_seed,
        "fuzz_count": config.fuzz_count,
        "states_per_puzzle": config.states_per_puzzle,
        "steps_per_state": config.steps_per_state,
        "clingo_timeout_seconds": config.clingo_timeout_seconds,
        "seed": config.seed,
    }
    (output / "config.json").write_text(json.dumps(config_payload, indent=2) + "\n", encoding="utf-8")
    _write_jsonl(output / "step_cases.jsonl", [_case_row(row) for row in rows])
    _write_jsonl(output / "results.jsonl", rows)
    _write_jsonl(output / "disagreements.jsonl", disagreements)
    _write_jsonl(output / "counterexamples.jsonl", counterexamples)
    (output / "coverage.json").write_text(
        json.dumps(_coverage_payload(rows, sat_states), indent=2) + "\n", encoding="utf-8"
    )
    (output / "summary.md").write_text(_summary_markdown(manifest), encoding="utf-8")
    _write_design_note(output)
    return manifest


def _gate_status(
    unsound_accepts: int,
    local_disagrees: int,
    stats: dict[str, Any],
    *,
    fuzz_count: int,
) -> str:
    if unsound_accepts > 0 or local_disagrees > 0:
        return "fail"
    if fuzz_count < FUZZ_MIN_COUNT:
        return "blocked"
    if stats["lean_rejected_semantic_count"] == 0:
        return "blocked"
    return "pass"


def _summarize(
    rows: list[dict[str, Any]],
    sat_states: list[dict[str, Any]],
    unsound_accepts: int,
    local_disagrees: int,
) -> dict[str, Any]:
    rule_counts: Counter[str] = Counter()
    clue_counts: Counter[str] = Counter()
    op_counts: Counter[str] = Counter()
    lean_kind_counts: Counter[str] = Counter()
    state_sat_status_counts: Counter[str] = Counter()
    accepted_local_forced = 0
    rejected_local_forced = 0
    accepted_local_unforced = 0
    rejected_local_unforced = 0
    for row in rows:
        state_sat_status_counts[row.get("state_sat_status", "unknown")] += 1
    for row in sat_states:
        rule = row.get("rule")
        if rule:
            rule_counts[rule] += 1
        clue_type = row.get("clue_type")
        if clue_type:
            clue_counts[clue_type] += 1
        op = (row.get("step") or {}).get("op")
        if op:
            op_counts[op] += 1
        lean_kind_counts[row.get("lean_result", {}).get("kind", "UNKNOWN")] += 1
        local = row.get("local_oracle") or {}
        if not row.get("is_local_differential_rule"):
            continue
        local_forced = local.get("status") == "unsat"
        if row.get("lean_accepted"):
            if local_forced:
                accepted_local_forced += 1
            else:
                accepted_local_unforced += 1
        else:
            if local_forced:
                rejected_local_forced += 1
            else:
                rejected_local_unforced += 1
    grid_distribution: Counter[str] = Counter()
    for row in sat_states:
        grid_distribution[row.get("grid", "unknown")] += 1
    semantic_steps = sum(op_counts.values())
    return {
        "total_cases": len(rows),
        "sat_consistent_states": len(sat_states),
        "state_sat_status_counts": dict(state_sat_status_counts),
        "lean_accepted_step_count": sum(1 for row in sat_states if row.get("lean_accepted")),
        "lean_rejected_semantic_count": sum(
            1 for row in sat_states
            if (row.get("step") or {}).get("op") in {"place", "eliminate"}
            and not row.get("lean_accepted")
        ),
        "global_unsound_accept_count": unsound_accepts,
        "local_differential_disagree_count": local_disagrees,
        "accepted_local_forced": accepted_local_forced,
        "rejected_local_forced": rejected_local_forced,
        "accepted_local_unforced": accepted_local_unforced,
        "rejected_local_unforced": rejected_local_unforced,
        "rule_counts": dict(rule_counts),
        "clue_type_counts": dict(clue_counts),
        "op_counts": dict(op_counts),
        "lean_kind_counts": dict(lean_kind_counts),
        "sat_state_grid_distribution": dict(grid_distribution),
        "semantic_step_count": semantic_steps,
    }


def _coverage_payload(rows: list[dict[str, Any]], sat_states: list[dict[str, Any]]) -> dict[str, Any]:
    rules = {rule: 0 for rule in PLACE_RULES + ELIMINATE_RULES}
    clue_types = {clue_type: 0 for clue_type in CLUE_TYPES}
    ops = {"place": 0, "eliminate": 0}
    for row in sat_states:
        rule = row.get("rule")
        if rule in rules:
            rules[rule] += 1
        clue_type = row.get("clue_type")
        if clue_type in clue_types:
            clue_types[clue_type] += 1
        op = (row.get("step") or {}).get("op")
        if op in ops:
            ops[op] += 1
    return {
        "rules_covered": sum(1 for value in rules.values() if value > 0),
        "rules_total": len(rules),
        "rule_counts": rules,
        "clue_types_covered": sum(1 for value in clue_types.values() if value > 0),
        "clue_types_total": len(clue_types),
        "clue_type_counts": clue_types,
        "op_counts": ops,
        "supported_differential_rules": sorted(SUPPORTED_DIFFERENTIAL_RULES),
    }


def _summary_markdown(manifest: dict[str, Any]) -> str:
    summary = manifest["summary"]
    corpus = manifest["corpus_provenance"]
    return f"""# Stage 3 stepwise G1 gate

Status: **{manifest['status'].upper()}**

- Seed: {manifest['seed']} (fuzz seed {manifest['fuzz_seed']})
- clingo version: {manifest['clingo_version']}
- Real/gold puzzle count: {corpus.get('stage2a_corpus_count', 0)}
- Fuzzed puzzle count: {corpus.get('fuzz_count', 0)}
- Total SAT-consistent states sampled: {summary['sat_consistent_states']}
- Total local step queries: {summary['semantic_step_count']}
- Lean-accepted steps: {summary['lean_accepted_step_count']}
- Lean-rejected semantic steps: {summary['lean_rejected_semantic_count']}
- Per-rule counts: {summary['rule_counts']}
- Per-clue-type counts: {summary['clue_type_counts']}
- Placement vs elimination counts: {summary['op_counts']}
- Grid-size distribution: {summary['sat_state_grid_distribution']}

## Headline metrics

- Candidate-level G1: see the rerun of stage3b_differential_candidates (independent gate directory).
- Stepwise global soundness: **unsound Lean accepts = {summary['global_unsound_accept_count']}**
- Stepwise justification-local differential: **disagreements = {summary['local_differential_disagree_count']}**

The exit criterion is:

* candidate G1: zero disagreements (existing gate definition)
* stepwise global soundness: zero unsound accepted steps over the recorded corpus
* stepwise local differential: zero Lean↔clingo disagreements over the recorded supported-rule corpus
"""


def _case_row(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "case_id": row["case_id"],
        "puzzle_id": row["puzzle_id"],
        "puzzle_kind": row["puzzle_kind"],
        "grid": row["grid"],
        "state_index": row.get("state_index"),
        "step_index": row.get("step_index"),
        "step": row.get("step"),
        "state_sat_status": row.get("state_sat_status"),
        "included_in_corpus": row.get("included_in_corpus", False),
        "rule": row.get("rule"),
        "clue_type": row.get("clue_type"),
    }


def _write_design_note(output: Path) -> None:
    if (output / "DESIGN.md").is_file():
        return
    (output / "DESIGN.md").write_text(DESIGN_NOTE, encoding="utf-8")


DESIGN_NOTE = """# Stage 3 stepwise G1 — design note

## What this gate compares

The gate tests the trusted Lean ``StepKernel`` against two independent clingo
oracles. The oracles encode only the structural bijection and per-house choice
constraints, plus the puzzle's clues, plus the partial ``StepState`` lowered
into ``at(C,V,H)`` facts. They deliberately do not re-implement any Lean rule
in Python.

## Why two oracles

A stepwise kernel can accept a step for two distinct reasons:

1. The step is **globally forced** by the puzzle and the current state. Every
   satisfying completion of the puzzle+state places the value in that house
   (for ``place``) or never places the value in that house (for ``eliminate``).
2. The cited justification is **locally sufficient** under the structural
   bijection and current state.

Global entailment is the blocking trust claim: if Lean accepts a step that is
not globally forced, Lean has emitted an unsound verdict over the puzzle.

Justification-local entailment is the *StepKernel-as-cited-rule-checker*
contract. The kernel is allowed to reject a globally entailed step if the
cited rule does not itself force the move. Therefore the differential gate
isolates those two questions and reports them separately.

## Oracles

### Global entailment

```text
Puzzle   = bijection base + all clues
State    = placed cells forced + non-placed cells enumerated over `possible`
Query    = base + state + forbid step atom
          place(item, house)   ⇒ forbid  at(item, house)
          eliminate(item, house) ⇒ forbid  not at(item, house)
Result   = UNSAT ⇒ globally forced; SAT ⇒ counterexample model recorded
```

### Justification-local entailment

```text
For clue-backed rules:
  Query  = bijection base + state + ONLY the single cited clue
For bijection rules:
  Query  = bijection base + state   (no cited clue)
Result   = same as global; reported alongside the global verdict per case
```

## Corpus

* **Gold**: the 1,000 rows of ``compiled_problems.jsonl`` re-emitted as
  ``schema_version 0.2`` problem.json files by the committed
  ``problem_fabricator``. No external ``data/zebralogic/source.json`` is
  required.
* **Fuzzed**: 10,000+ deterministically generated ZebraLogic puzzles built
  from a fixed RNG seed and the bounded CATEGORY_POOL / VALUE_POOL vocabularies.
  Each generated puzzle is checked against ``clingo`` (development-only oracle)
  via the gold ``check_candidate`` path so the gate trusts Lean for the verdict
  and clingo only as the differential semantic reference.

## Step proposals

The ``step_proposer`` enumerates place/eliminate steps over a SAT-consistent
partial state. It includes:

* singleton-cell and singleton-value bijection cases
* ``given_found_at_place`` and ``given_not_at_eliminate`` for unary clues
* place from placed partner for ``same_house``/``direct_left``/``direct_right``
* single-neighbor place and no-possible-neighbor eliminate for ``side_by_side``
* singleton-distance place and no-possible-partner eliminate for ``one_between``
  /``two_between``
* impossible-order eliminate for ``left_of`` / ``right_of``

The proposer does not filter for whether Lean would accept the step. Both
oracles decide the ground truth.

## What is excluded from the differential denominator

* Static / interface rejection codes (``malformed_step``, ``unknown_category``,
  ``unknown_value``, ``house_out_of_range``, ``unknown_clue_ref``,
  ``rule_clue_mismatch``, ``unsupported_rule``).
* Conclusion path (``solved_conclusion`` and ``contradiction_detection``) —
  these delegate to CheckerCore, not to a local place/eliminate rule.

These are deterministic StepKernel validation tests and remain covered by the
existing ``stage3c_step_kernel`` example gate. They are explicitly excluded
from the differential denominator here.

## Why the gate can fail closed

* Every ``ACCEPT_STEP`` is paired with a global entailment query. UNSAT is
  required; SAT triggers ``unsound_accept`` disagreement and freezes the
  counterexample model in ``counterexamples.jsonl``.
* Every supported local rule's verdict is paired with an independent clingo
  query that ignores the rest of the puzzle's clues. A disagreement freezes
  the case in ``disagreements.jsonl``.
* Inconsistent generated states (state_is_sat != sat) are recorded separately
  and discarded from the comparison corpus. They never inflate the
  ``unsound_accept`` count.
"""


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def run_gate(
    compiled_path: Path,
    reference_dir: Path,
    output_dir: Path,
    seed: int,
    fuzz_seed: int,
    fuzz_count: int,
    states_per_puzzle: int,
    steps_per_state: int,
    clingo_timeout_seconds: float,
) -> dict[str, Any]:
    config = GateConfig(
        compiled_path=Path(compiled_path),
        reference_dir=Path(reference_dir),
        output_dir=Path(output_dir),
        fuzz_seed=fuzz_seed,
        fuzz_count=fuzz_count,
        states_per_puzzle=states_per_puzzle,
        steps_per_state=steps_per_state,
        clingo_timeout_seconds=clingo_timeout_seconds,
        seed=seed,
        lean_executable=ROOT / ".lake" / "build" / "bin" / "sparse-ir-lean",
        fuzz_grid_distribution={},
    )
    return _run_gate(config)